FROM node:20

WORKDIR /app

# وابستگی سیستمی sharp
RUN apt-get update && apt-get install -y \
  libvips \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install --legacy-peer-deps

RUN npm install -g @nestjs/cli

CMD ["npm", "run", "start:dev"]
