FROM python-ai-core

USER root

RUN --mount=type=bind,source=downloaded_wheels,target=/wheels,readonly \
    --mount=type=cache,target=/root/.cache/pip \
    pip install --no-index --find-links=/wheels \
        numpy \
        pandas \
        scikit-learn \
        xgboost \
        joblib \
        apscheduler \
        psutil

USER appuser

CMD ["bash"]
