FROM python-ai-nlp:latest

WORKDIR /app
COPY . .
ENV PYTHONPATH=/app

RUN --mount=type=bind,source=downloaded_wheels,target=/wheels,readonly \
    --mount=type=cache,target=/root/.cache/pip \
    pip install --no-index --find-links=/wheels \
        networkx


CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]